// Simulated FPGA ring-oscillator PUF with fuzzy extractor.
//
// Models two protocol-relevant properties of a real silicon PUF:
//
//   1. Uncloneability — the KEK can only be regenerated by an entity that
//      holds the device's internal PUF seed. The seed models the intrinsic
//      silicon variation of a particular FPGA and is never writable.
//   2. Noisy-but-recoverable — a real read of the PUF is slightly different
//      each time due to thermal / voltage noise, recovered by a fuzzy
//      extractor that stacks two classical techniques:
//        (a) majority vote across N reads (error prob ~ C(N, N/2) p^(N/2) ),
//        (b) a code-offset XOR sketch with a freshly-sampled reference,
//            yielding the fuzzy extractor of Dodis, Reyzin, Smith 2004
//            (Eurocrypt 2004, §4.1).
//      The result is fed into HKDF to produce a uniform 256-bit KEK.
//
// This is not a real silicon PUF. Lacking measured silicon, the reference
// simulator assumes an IDEALIZED RELIABLE PUF: the injected read-noise is 0
// (config.PUF_NOISE_PROB), so a correct device always regenerates its KEK,
// while a wrong device still fails deterministically (different intrinsic
// secret => tag mismatch). The fuzzy-extractor machinery below is kept intact
// so a nonzero noise rate can be re-enabled; modelling realistic silicon noise
// and reliability is future work.

import { hkdf, sha256, timingSafeEqual } from "./primitives.ts";
import {
  PUF_RESPONSE_BITS,
  PUF_NOISE_PROB,
  PUF_MAJORITY_READS,
} from "../config.ts";
import { createHash } from "node:crypto";
import { randomBytes, randomFloat } from "./rng.ts";

const PUF_BYTES = PUF_RESPONSE_BITS / 8;

/**
 * PUF seed — models the per-device, per-fabric silicon variation. In real
 * hardware this is never written; it emerges from manufacturing and is read
 * out by configurable ring oscillators.
 */
export interface PufSeed {
  id: string;
  secret: Buffer; // 32 random bytes unique to the device
}

/** Helper data that is safe to store in eFuse/flash alongside the black key. */
export interface PufHelperData {
  challenge: Buffer;
  sketch: Buffer; // code-offset sketch
  // Tag lets regeneration fail loudly if the helper data is tampered with.
  tag: Buffer;
}

export function generatePufSeed(id: string): PufSeed {
  return { id, secret: randomBytes(32) };
}

/** A single *noisy* raw read of the PUF at a given challenge. */
function noisyRawRead(seed: PufSeed, challenge: Buffer): Buffer {
  // The "clean" response is a deterministic function of (seed, challenge).
  // Each bit is flipped independently with probability PUF_NOISE_PROB.
  const clean = createHash("sha256")
    .update(seed.secret)
    .update(challenge)
    .digest()
    .subarray(0, PUF_BYTES);

  const out = Buffer.from(clean);
  for (let i = 0; i < out.length; i++) {
    let b = out[i];
    for (let bit = 0; bit < 8; bit++) {
      if (randomFloat() < PUF_NOISE_PROB) b ^= 1 << bit;
    }
    out[i] = b;
  }
  return out;
}

/** Majority vote over several noisy reads (Dodis et al. 2004, §3.3). */
function stableRead(seed: PufSeed, challenge: Buffer): Buffer {
  const reads: Buffer[] = [];
  for (let i = 0; i < PUF_MAJORITY_READS; i++) {
    reads.push(noisyRawRead(seed, challenge));
  }
  const out = Buffer.alloc(PUF_BYTES);
  for (let i = 0; i < PUF_BYTES; i++) {
    for (let bit = 0; bit < 8; bit++) {
      let ones = 0;
      for (const r of reads) if ((r[i] >> bit) & 1) ones++;
      if (ones > PUF_MAJORITY_READS / 2) out[i] |= 1 << bit;
    }
  }
  return out;
}

/** Enroll a PUF: returns the KEK and the helper data to persist. */
export function pufEnroll(seed: PufSeed): { kek: Buffer; helper: PufHelperData } {
  const challenge = randomBytes(16);
  const response = stableRead(seed, challenge);

  // Code-offset fuzzy extractor: sample a uniform reference r; publish
  // sketch = response XOR r. Regeneration recovers r by XORing sketch
  // with a fresh majority-vote response (Dodis et al. 2004, §4.1).
  const reference = randomBytes(PUF_BYTES);
  const sketch = Buffer.alloc(PUF_BYTES);
  for (let i = 0; i < PUF_BYTES; i++) sketch[i] = response[i] ^ reference[i];

  const tag = sha256(Buffer.concat([challenge, sketch, reference]));
  // @secret-escapes: kek is returned to pufEnroll's caller (the drone
  // enrollment path) and disposed there with kek.fill(0) after the
  // black-key wrap.
  const kek = hkdf(reference, challenge, "litezero/kek", 32);
  reference.fill(0);
  return { kek, helper: { challenge, sketch, tag } };
}

/** Regenerate the KEK from the PUF + helper data. */
export function pufRegenerate(seed: PufSeed, helper: PufHelperData): Buffer {
  const response = stableRead(seed, helper.challenge);
  const reference = Buffer.alloc(PUF_BYTES);
  for (let i = 0; i < PUF_BYTES; i++) reference[i] = response[i] ^ helper.sketch[i];

  const expectTag = sha256(
    Buffer.concat([helper.challenge, helper.sketch, reference]),
  );
  // Constant-time tag comparison: the tag gates KEK regeneration and is
  // derived over the recovered (secret) reference, so it is compared with the
  // same constant-time primitive as every other MAC/tag in the protocol.
  if (!timingSafeEqual(expectTag, helper.tag)) {
    throw new Error("PUF regeneration failed: helper data tampered or wrong device");
  }
  return hkdf(reference, helper.challenge, "litezero/kek", 32);
}
